### ISSUE TITLE
请问一下您的这个clover是什么版本

### ISSUE THREAD

**Issue by kiss4437** [gaoliang/ASUS-X550JX-Hackintosh#2]
首先非常感谢您分享。
在我使用的时候，也遇到了卡优盘win错误。我又换了一个4414版本的clover。不过好像问题挺多的，BCm43225的无线可以驱动，蓝牙驱动不了。并且，usb 接口也有个识别不到了。我想问一下您这个clover是什么版本的，我想用同版本的试试。

**Comment by gaoliang** [comment]
抱歉才看到，用的是4369

**Comment by kiss4437** [comment]
感谢您的回答，新年好！
用了同级的clover问题好像依然还存在。期待您的更新
谢谢
