### ISSUE TITLE
fx50jk可以用么

### ISSUE THREAD

**Issue by cayzlh** [gaoliang/ASUS-X550JX-Hackintosh#6]
fx50jk可以用么

**Comment by gaoliang** [comment]
没有试过， 不过配置差不多应该可以参考一下

**Comment by chenanyu** [comment]
好的, 不过我已经黑完了..下次重装的话, 可以试试你这个

**Comment by chenanyu** [comment]
你好， 请问你遇到过vga外接显示器花屏的问题么。 这个问题应该怎么解决呢，可以加QQ支持一下么：243689185
